[env:UART]
platform  = ststm32
board     = genericSTM32G431CB
framework = stm32cube

upload_protocol = stlink
debug_tool      = stlink

monitor_port    = COM8
monitor_speed   = 9600


build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32G431xx
    -ICore/Inc
    -IDrivers/CMSIS/Include
    -IDrivers/CMSIS/Device/ST/STM32G4xx/Include
    -IDrivers/STM32G4xx_HAL_Driver/Inc
    -IDrivers/STM32G4xx_HAL_Driver/Inc/Legacy

; ↓ THIS IS THE KEY FIX
; Use ONLY your local Drivers/
; Ignore PlatformIO internal HAL completely
build_src_filter =
    +<../Core/Src/*.c>
    +<../Drivers/STM32G4xx_HAL_Driver/Src/*.c>
    -<../.pio/*>

; Tell PlatformIO NOT to use
; its own HAL driver files
custom_framework_stm32cube_build_flags =
    -DHAL_MODULE_ENABLED
; Exclude PlatformIO internal HAL
; Use only YOUR local Drivers/ folder
lib_ignore = HAL
