#include "main.h"
#include <string.h>
#include <stdio.h>

/* ─── Handle declarations (generated by CubeMX) ─── */
UART_HandleTypeDef huart2;
TIM_HandleTypeDef  htim1;
TIM_HandleTypeDef  htim6;

/* ════════════════════════════════════════════════
   SERVO STATE
   ════════════════════════════════════════════════ */
#define CCR_STOP     1500
#define CCR_STEP     80      // speed increment per level
#define CCR_MAX_CW   1900    // level 5 CW
#define CCR_MIN_CCW  1100    // level 5 CCW
#define SPEED_MAX    5

typedef enum {
    DIR_STOP = 0,
    DIR_CW   = 1,
    DIR_CCW  = -1
} Direction_t;

int16_t     g_ccr       = CCR_STOP;
int8_t      g_direction = DIR_STOP;
uint8_t     g_speed     = 0;
uint16_t    g_telem_cnt = 0;

/* ════════════════════════════════════════════════
   UART BUFFER
   ════════════════════════════════════════════════
   Ring buffer approach:
   ISR writes bytes in → main loop reads out
   No data loss even at high speed
   ════════════════════════════════════════════════ */
#define RX_BUF_SIZE  64

uint8_t  rx_byte;               // single DMA/IT byte
char     rx_ring[RX_BUF_SIZE];  // ring buffer
uint8_t  rx_head = 0;           // ISR writes here
uint8_t  rx_tail = 0;           // main reads here
char     cmd_buf[32];           // assembled command
uint8_t  cmd_idx = 0;
uint8_t  cmd_ready = 0;

/* ════════════════════════════════════════════════
   FUNCTION PROTOTYPES
   ════════════════════════════════════════════════ */
void SystemClock_Config(void);
void MX_USART2_UART_Init(void);
void MX_TIM1_Init(void);
void MX_TIM6_Init(void);
void servo_apply(void);
void servo_stop(void);
void parse_command(char *cmd);
void send_status(void);
void process_ring_buffer(void);

/* ════════════════════════════════════════════════
   MAIN
   ════════════════════════════════════════════════ */
int main(void) {

    HAL_Init();
    SystemClock_Config();

    MX_USART2_UART_Init();
    MX_TIM1_Init();
    MX_TIM6_Init();

    /* Start PWM — servo neutral on boot */
    HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);
    __HAL_TIM_SET_COMPARE(&htim1,
                           TIM_CHANNEL_1,
                           CCR_STOP);

    /* Start 1ms ticker */
    HAL_TIM_Base_Start_IT(&htim6);

    /* Start UART interrupt receive */
    HAL_UART_Receive_IT(&huart2, &rx_byte, 1);

    /* Welcome message */
    char *welcome =
        "\r\n=== Servo UART Controller ===\r\n"
        "CW  CCW  UP  DN  STP  RST\r\n"
        "==============================\r\n";
    HAL_UART_Transmit(&huart2,
                      (uint8_t*)welcome,
                      strlen(welcome),
                      HAL_MAX_DELAY);

    /* ── Main Loop ── */
    while (1) {
        /* Process ring buffer → assemble commands */
        process_ring_buffer();

        /* Execute command if ready */
        if (cmd_ready) {
            cmd_ready = 0;
            parse_command(cmd_buf);
            memset(cmd_buf, 0, sizeof(cmd_buf));
            cmd_idx = 0;
        }
    }
}

/* ════════════════════════════════════════════════
   RING BUFFER PROCESSOR
   Runs in main loop — safely reads bytes
   that ISR wrote into ring buffer
   ════════════════════════════════════════════════ */
void process_ring_buffer(void) {
    while (rx_tail != rx_head) {
        char c = rx_ring[rx_tail];
        rx_tail = (rx_tail + 1) % RX_BUF_SIZE;

        if (c == '\n' || c == '\r') {
            if (cmd_idx > 0) {
                cmd_buf[cmd_idx] = '\0';
                cmd_ready = 1;
                return;   // process one cmd at a time
            }
        } else if (cmd_idx < sizeof(cmd_buf) - 1) {
            cmd_buf[cmd_idx++] = c;
        }
    }
}

/* ════════════════════════════════════════════════
   UART RX INTERRUPT CALLBACK
   ISR writes byte into ring buffer → returns fast
   Main loop processes it safely
   ════════════════════════════════════════════════ */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *h) {
    if (h->Instance == USART2) {
        /* Write byte into ring buffer */
        rx_ring[rx_head] = rx_byte;
        rx_head = (rx_head + 1) % RX_BUF_SIZE;

        /* Re-arm interrupt */
        HAL_UART_Receive_IT(&huart2, &rx_byte, 1);
    }
}

/* ════════════════════════════════════════════════
   COMMAND PARSER
   ════════════════════════════════════════════════ */
void parse_command(char *cmd) {

    if (strcmp(cmd, "CW") == 0) {
        g_direction = DIR_CW;
        if (g_speed == 0) g_speed = 1;
        servo_apply();
    }
    else if (strcmp(cmd, "CCW") == 0) {
        g_direction = DIR_CCW;
        if (g_speed == 0) g_speed = 1;
        servo_apply();
    }
    else if (strcmp(cmd, "UP") == 0) {
        if (g_speed < SPEED_MAX) g_speed++;
        servo_apply();
    }
    else if (strcmp(cmd, "DN") == 0) {
        if (g_speed > 0) g_speed--;
        if (g_speed == 0) g_direction = DIR_STOP;
        servo_apply();
    }
    else if (strcmp(cmd, "STP") == 0) {
        servo_stop();
    }
    else if (strcmp(cmd, "RST") == 0) {
        servo_stop();
    }

    send_status();
}

/* ════════════════════════════════════════════════
   SERVO CONTROL
   ════════════════════════════════════════════════ */
void servo_apply(void) {
    g_ccr = CCR_STOP + (g_direction * g_speed * CCR_STEP);

    if (g_ccr > CCR_MAX_CW)  g_ccr = CCR_MAX_CW;
    if (g_ccr < CCR_MIN_CCW) g_ccr = CCR_MIN_CCW;

    __HAL_TIM_SET_COMPARE(&htim1,
                           TIM_CHANNEL_1,
                           g_ccr);
}

void servo_stop(void) {
    g_direction = DIR_STOP;
    g_speed     = 0;
    g_ccr       = CCR_STOP;
    __HAL_TIM_SET_COMPARE(&htim1,
                           TIM_CHANNEL_1,
                           CCR_STOP);
}

/* ════════════════════════════════════════════════
   TELEMETRY — sends status back to Python
   Format: "S:CW:3:68\n"
           S = status packet
           CW/CCW/STOP = direction
           3 = speed level
           68 = speed percentage
   ════════════════════════════════════════════════ */
void send_status(void) {
    char msg[48];
    char *dir = (g_direction == DIR_CW)  ? "CW"  :
                (g_direction == DIR_CCW) ? "CCW" : "STOP";
    uint8_t pct = (g_speed * 100) / SPEED_MAX;

    snprintf(msg, sizeof(msg),
             "S:%s:%d:%d\n",
             dir, g_speed, pct);

    HAL_UART_Transmit(&huart2,
                      (uint8_t*)msg,
                      strlen(msg),
                      HAL_MAX_DELAY);
}

/* ════════════════════════════════════════════════
   TIM6 1ms INTERRUPT
   Sends telemetry to Python every 200ms
   automatically — no command needed
   ════════════════════════════════════════════════ */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *h) {
    if (h->Instance == TIM6) {
        g_telem_cnt++;
        if (g_telem_cnt >= 200) {
            g_telem_cnt = 0;
            send_status();   // auto telemetry
        }
    }
}
/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/* ── These MUST exist ── */
void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1_BOOST);

    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState       = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState   = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource  = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM       = RCC_PLLM_DIV4;
    RCC_OscInitStruct.PLL.PLLN       = 85;
    RCC_OscInitStruct.PLL.PLLP       = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ       = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR       = RCC_PLLR_DIV2;
    HAL_RCC_OscConfig(&RCC_OscInitStruct);

    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK |
                                       RCC_CLOCKTYPE_SYSCLK |
                                       RCC_CLOCKTYPE_PCLK1 |
                                       RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
    HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4);
}

void Error_Handler(void)
{
    __disable_irq();
    while (1) { }
}
